# Generated by Django 5.2.12 on 2026-03-13 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNT', '0001_initial'),
        ('DEPARTMENT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='DEPARTMENT.department'),
        ),
    ]
