# Generated by Django 5.2.12 on 2026-03-09 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNT', '0002_alter_usermodel_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'UserModel', 'verbose_name_plural': 'UserModels'},
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('commissioner', 'Commissioner'), ('deputy_commissioner', 'Deputy Commissioner'), ('municipal_officer', 'Municipal Officer'), ('sanitation_officer', 'Sanitation Officer'), ('health_officer', 'Health Officer'), ('water_supply_officer', 'Water Supply Officer'), ('electricity_officer', 'Electricity Officer'), ('road_transport_officer', 'Road & Transport Officer'), ('environment_officer', 'Environment Officer'), ('fire_department_officer', 'Fire Department Officer'), ('police_officer', 'Police Officer'), ('traffic_officer', 'Traffic Officer'), ('housing_officer', 'Housing Officer'), ('public_works_officer', 'Public Works Officer'), ('education_officer', 'Education Officer'), ('it_officer', 'IT Officer'), ('maintenance_officer', 'Maintenance Officer'), ('waste_management_officer', 'Waste Management Officer'), ('zonal_officer', 'Zonal Officer'), ('ward_officer', 'Ward Officer')], max_length=200)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('landmark', models.CharField(max_length=50)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
