# Generated by Django 5.2.12 on 2026-03-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNT', '0003_alter_usermodel_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
