# Generated by Django 5.2.12 on 2026-03-16 06:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNT', '0004_alter_usermodel_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_picture'),
        ),
    ]
