# Generated by Django 5.2.12 on 2026-03-13 06:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ACCOUNT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='Department name must be at least 2 characters long.')])),
                ('department_code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='Department code must be at least 2 characters long.'), django.core.validators.RegexValidator(message='Department code must be uppercase and alphanumeric.', regex='^[A-Z0-9]+$')])),
                ('department_email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('office_address', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10, message='Office address must be at least 10 characters long.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='ACCOUNT.officer')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Category name must be at least 3 characters long.')])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(5, message='Description must be at least 5 characters long.')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='DEPARTMENT.department')),
            ],
        ),
    ]
