# Generated by Django 5.2.12 on 2026-03-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEPARTMENT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Water Leakage', 'Water Leakage'), ('No Water Supply', 'No Water Supply'), ('Pothole Issue', 'Pothole Issue'), ('Broken Road', 'Broken Road'), ('Power Cut', 'Power Cut'), ('Street Light Not Working', 'Street Light Not Working'), ('Garbage Issue', 'Garbage Issue'), ('Drain Blockage', 'Drain Blockage')], max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('Water Department', 'Water Department'), ('Road Department', 'Road Department'), ('Electricity Department', 'Electricity Department'), ('Sanitation Department', 'Sanitation Department'), ('Drainage Department', 'Drainage Department'), ('Street Light Department', 'Street Light Department')], max_length=100),
        ),
    ]
